name: "dingtalk-test"
on:
  push:
    branches:
      - test/*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      if: always()
      env:
        DINGTALK_ACCESS_TOKEN: ${{ secrets.DINGTALK_ACCESS_TOKEN }}
      with:
        text: '测试--钉钉消息通知测试'

  # success-notify:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - run: exit 0
  #   - name: run action
  #     uses: ./
  #     if: always()
  #     env:
  #       DINGTALK_ACCESS_TOKEN: ${{ secrets.DINGTALK_ACCESS_TOKEN }}
  #     with:
  #       msgtype: markdown
  #       notify_when: 'success'
  #       title: '代码测试通过'
  #       text: |
  #         **<font color=#00FF00 size=4>构建成功</font>**

  #         ### GitHub Action workflow **${{ github.workflow }}** 构建成功

  # failure-notify:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - run: exit 1
  #   - name: run action
  #     uses: ./
  #     if: always()
  #     env:
  #       DINGTALK_ACCESS_TOKEN: ${{ secrets.DINGTALK_ACCESS_TOKEN }}
  #     with:
  #       msgtype: markdown
  #       notify_when: 'failure'
  #       title: '代码测试发现异常'
  #       text: |
  #         **<font color=#FF0000 size=4>构建失败</font>**

  #         ### GitHub Action workflow **${{ github.workflow }}** 构建失败

  #         - 问题一
  #         - 问题二
  #         - 问题三