name: "dingtalk-test"
on:
  push:
    branches:
      - test/*

jobs:
  # before steps
  before:
    runs-on: ubuntu-latest
    steps:
    - run: echo "before steps"
    - run: exit 1


  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    needs: before
    steps:
    - uses: actions/checkout@v2
    - name: run action
      uses: ./
      if: always()
      env:
        DINGTALK_ACCESS_TOKEN: ${{ secrets.DINGTALK_ACCESS_TOKEN }}
      with:
        msgtype: link
        notify_when: 'failure'
        title: '这是一个链接通知'
        text: '测试--钉钉消息测试，链接测试'
