name: "dingtalk-test"
on:
  push:
    branches:
      - test/*

jobs:
  # test action works running from the graph
  success-notify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: exit 0
    - name: run action
      uses: ./
      if: always()
      env:
        DINGTALK_ACCESS_TOKEN: ${{ secrets.DINGTALK_ACCESS_TOKEN }}
      with:
        msgtype: markdown
        notify_when: 'success'
        title: '代码测试通过'
        text: |
          ### GitHub Action workflow **${{ github.workflow }}** 构建成功

  failure-notify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: exit 1
    - name: run action
      uses: ./
      if: always()
      env:
        DINGTALK_ACCESS_TOKEN: ${{ secrets.DINGTALK_ACCESS_TOKEN }}
      with:
        msgtype: markdown
        notify_when: 'failure'
        title: '代码测试发现异常'
        text: |
          ### GitHub Action workflow **${{ github.workflow }}** 构建失败 \n 代码发现异常